# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webcatch < Formula
  desc "Simple HTTP request inspector that captures and displays incoming requests in real-time"
  homepage "https://github.com/alwedo/webcatch"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alwedo/webcatch/releases/download/v0.4.1/webcatch_0.4.1_darwin_amd64.tar.gz"
      sha256 "4ca6112f4f66b51091b5768d48f204e0ff5890e44ee18a292360789f5319b57c"

      define_method(:install) do
        bin.install "webcatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alwedo/webcatch/releases/download/v0.4.1/webcatch_0.4.1_darwin_arm64.tar.gz"
      sha256 "e350d324d0074cbecbb25240f4b20eb94908fb85e77be0ae4fe7c851cc6e7eb9"

      define_method(:install) do
        bin.install "webcatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alwedo/webcatch/releases/download/v0.4.1/webcatch_0.4.1_linux_amd64.tar.gz"
      sha256 "32b05c4266d976a82d5cd5c84379376806e8d611a9999158dc251239c20e7f91"
      define_method(:install) do
        bin.install "webcatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alwedo/webcatch/releases/download/v0.4.1/webcatch_0.4.1_linux_arm64.tar.gz"
      sha256 "ba426768d96276596faae815f2fb576994c622874443b75765002c4e7c4d6b9d"
      define_method(:install) do
        bin.install "webcatch"
      end
    end
  end

  test do
    system "#{bin}/webcatch", "--version"
  end
end
