# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webcatch < Formula
  desc "Simple HTTP request inspector that captures and displays incoming requests in real-time"
  homepage "https://github.com/alwedo/webcatch"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alwedo/webcatch/releases/download/v0.4.0/webcatch_0.4.0_darwin_amd64.tar.gz"
      sha256 "5da7a5fc74db1eeb2def435f76fe5d7155b3150259446cfb29236fefb5e85f0c"

      define_method(:install) do
        bin.install "webcatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alwedo/webcatch/releases/download/v0.4.0/webcatch_0.4.0_darwin_arm64.tar.gz"
      sha256 "799545cc81b644f21581484641754c8e121dd4236bb29c8e0bb0dcd09aced014"

      define_method(:install) do
        bin.install "webcatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alwedo/webcatch/releases/download/v0.4.0/webcatch_0.4.0_linux_amd64.tar.gz"
      sha256 "9bd672288c349dc8eb277324e86d292449dc855bdd9a2a525912b7ecab052122"
      define_method(:install) do
        bin.install "webcatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alwedo/webcatch/releases/download/v0.4.0/webcatch_0.4.0_linux_arm64.tar.gz"
      sha256 "dd372525978acbaa8c3f0117a3a0f4a0dbe5f1386da6469eaf7679cf74e89beb"
      define_method(:install) do
        bin.install "webcatch"
      end
    end
  end

  test do
    system "#{bin}/webcatch", "--version"
  end
end
